---
ID: "ff372caa-0581-4119-aa74-ac179aecd657"
Parent: "01bcf357-6249-4e8b-aeef-8b6ea009753d"
Template: "01bcf357-6249-4e8b-aeef-8b6ea009753d"
Path: /sitecore/templates/Redirect Module/Versioned Redirect Pattern/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20111001T002952
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
